#!/usr/bin/env python3
import socket
import zmq
import os
import time
import signal

graceful_quit = False

def handler(signal, frame):
    global graceful_quit
    print("[CLIENT] Signal received. Exiting program")
    graceful_quit = True

def main():
    global graceful_quit
    signal.signal(signal.SIGTERM, handler)
    signal.signal(signal.SIGINT, handler)

    while not graceful_quit:
        socket1 = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
        socket1.connect(("server", 12345))

        socket2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
        socket2.connect(("server", 12345))

        socket2.send(b"TU VIEJA")
        socket1.send(b"EN TANGA")

        socket2.close()
        socket1.close()
        time.sleep(0.1)

    print("[CLIENT] Ctrl + C received. Finishing program")

if __name__ == "__main__":
    main()
