version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: server.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - AMOUNT_WORKERS=1

  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server