version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: server.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - AMOUNT_WORKERS=1

  client6:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server

  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server

  client0:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server

  client1:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server

  client2:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server

  client3:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server

  client4:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server

  client5:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - server
    depends_on:
      - server